//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cup.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cup.Languages.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default action:.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        internal static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple screen capturing tool.
        ///Made by ~sanlyx.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sanlyx.github.io/cup.
        /// </summary>
        internal static string AppURL {
            get {
                return ResourceManager.GetString("AppURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the application when I sign in.
        /// </summary>
        internal static string Autostart {
            get {
                return ResourceManager.GetString("Autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (built-in).
        /// </summary>
        internal static string BuiltIn {
            get {
                return ResourceManager.GetString("BuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new folder has been created. Click here to open it..
        /// </summary>
        internal static string DirectoryNotFoundBody {
            get {
                return ResourceManager.GetString("DirectoryNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access Captures folder.
        /// </summary>
        internal static string DirectoryNotFoundInstruction {
            get {
                return ResourceManager.GetString("DirectoryNotFoundInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shortcut has already been assigned to {0}.
        /// </summary>
        internal static string DuplicateHotKeyDescription {
            get {
                return ResourceManager.GetString("DuplicateHotKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut already in use.
        /// </summary>
        internal static string DuplicateHotKeyTitle {
            get {
                return ResourceManager.GetString("DuplicateHotKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The capture you&apos;ve just made has been saved..
        /// </summary>
        internal static string FileSavedBody {
            get {
                return ResourceManager.GetString("FileSavedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been saved.
        /// </summary>
        internal static string FileSavedInstruction {
            get {
                return ResourceManager.GetString("FileSavedInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL has been copied to the clipboard..
        /// </summary>
        internal static string FileUploadedBody {
            get {
                return ResourceManager.GetString("FileUploadedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been uploaded.
        /// </summary>
        internal static string FileUploadedInstruction {
            get {
                return ResourceManager.GetString("FileUploadedInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display legacy notifications.
        /// </summary>
        internal static string LegacyNotifications {
            get {
                return ResourceManager.GetString("LegacyNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captures.
        /// </summary>
        internal static string LocalDirectoryName {
            get {
                return ResourceManager.GetString("LocalDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no shortcut).
        /// </summary>
        internal static string NilHotKey {
            get {
                return ResourceManager.GetString("NilHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Actions directory….
        /// </summary>
        internal static string OpenActionsDirectory {
            get {
                return ResourceManager.GetString("OpenActionsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be saved. Please, review the folder permissions..
        /// </summary>
        internal static string SaveErrorBody {
            get {
                return ResourceManager.GetString("SaveErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file.
        /// </summary>
        internal static string SaveErrorInstruction {
            get {
                return ResourceManager.GetString("SaveErrorInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep a local copy of each screenshot.
        /// </summary>
        internal static string SaveLocally {
            get {
                return ResourceManager.GetString("SaveLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot format:.
        /// </summary>
        internal static string ScreenshotFormat {
            get {
                return ResourceManager.GetString("ScreenshotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut:.
        /// </summary>
        internal static string ScreenshotHotKey {
            get {
                return ResourceManager.GetString("ScreenshotHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take screenshot.
        /// </summary>
        internal static string TakeScreenshot {
            get {
                return ResourceManager.GetString("TakeScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be uploaded. Try again in a few minutes..
        /// </summary>
        internal static string UploadErrorBody {
            get {
                return ResourceManager.GetString("UploadErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload file.
        /// </summary>
        internal static string UploadErrorInstruction {
            get {
                return ResourceManager.GetString("UploadErrorInstruction", resourceCulture);
            }
        }
    }
}
